export const OtpType = {
	REGISTER_VERIFICATION: 'REGISTER_VERIFICATION',
	RESET_PASSWORD: 'RESET_PASSWORD',
	CHANGE_EMAIL: 'CHANGE_EMAIL',
} as const;

export type OtpType = 'REGISTER_VERIFICATION' | 'RESET_PASSWORD' | 'CHANGE_EMAIL';
export const OtpTypeAccepted = [OtpType.REGISTER_VERIFICATION, OtpType.RESET_PASSWORD, OtpType.CHANGE_EMAIL] as const;
